include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Stil kuralları
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    file_names: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_check_on_nullable_type_parameter: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_single_quotes: true
    prefer_void_to_null: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_checks: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    use_rethrow_when_possible: true
    valid_regexps: true

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated/**"
    - "lib/gen/**"
